






//CATEGORIES
export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST'
export const ADD_CATEGORY = 'ADD_CATEGORY'

//PRODUCT
export const GET_CATEGORY_PRODUCT = "GET_CATEGORY_PRODUCT"
export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST"
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL"
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'



//CART



export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM'

export const GET_CART_LIST = 'GET_CART_LIST'

export const ADD_TO_CART = 'ADD_TO_CART'
export type ADD_TO_CART = typeof ADD_TO_CART


export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export type REMOVE_FROM_CART = typeof REMOVE_FROM_CART


//FILTER
export const SET_FILTER = 'SET_FILTER'
export const SET_TEXT_FILTER = 'SET_TEXT_FILTER'
export const RESET_FILTER = 'RESET_FILTER'






