


export const ADD_TO_CART = 'ADD_TO_CART'
export type ADD_TO_CART = typeof ADD_TO_CART


export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export type REMOVE_FROM_CART = typeof REMOVE_FROM_CART



//CATEGORIES
export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST'
export const ADD_CATEGORY = 'ADD_CATEGORY'

//PRODUCT
export const GET_CATEGORY_PRODUCT = "GET_CATEGORY_PRODUCT"
export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST"
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL"
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'





export const GET_MENU_LIST = "GET_MENU_LIST"
export const GET_PRODUCT_INFO = "GET_PRODUCT_INFO"
export const INCREMENT_PRODUCT_QUANTITY = "INCREMENT_PRODUCT_QUANTITY"
export const DECREMENT_PRODUCT_QUANTITY = "DECREMENT_PRODUCT_QUANTITY"

